apiVersion: v1
entries:
  aks-basic-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: azure
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-17T11:44:50.68271025Z"
    description: A Helm chart for deploying AKS basic cluster
    digest: 95bb0e70f6662334aa11a37bfb8215d04b88a45d6833cc719fc8821517f93140
    keywords:
    - azure
    - basic
    - cluster
    - kubernetes
    - aks
    name: aks-basic-cluster
    type: application
    urls:
    - aks-basic-cluster-0.1.0.tgz
    version: 0.1.0
  aks-intermediate-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: digital
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-17T11:44:50.682880919Z"
    description: A Helm chart for deploying AKS intermediate cluster
    digest: 478ac985d01235d01c7aa89a55abb11b7ea457c6be4922f8f12880585de2595d
    keywords:
    - azure
    - intermediate
    - cluster
    - kubernetes
    - aks
    name: aks-intermediate-cluster
    type: application
    urls:
    - aks-intermediate-cluster-0.1.0.tgz
    version: 0.1.0
  digital-basic-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: digital
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-17T11:44:50.683083518Z"
    description: A Helm chart for deploying digital basic cluster
    digest: 83b077c306fb39ea679b595ac19bee3447a30f289229098c647619aa1fc357d7
    keywords:
    - digital-ocean
    - basic
    - cluster
    - kubernetes
    name: digital-basic-cluster
    type: application
    urls:
    - digital-basic-cluster-0.1.0.tgz
    version: 0.1.0
generated: "2024-12-17T11:44:50.682399099Z"
