apiVersion: v1
entries:
  aks-advance-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: azure
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.651112909Z"
    description: A Helm chart for deploying AKS advance cluster
    digest: 0e2eea0c3295c2a851f2ea69a8b57f78fafaffce2980bf7ec23f35171d847ea6
    keywords:
    - azure
    - advance
    - cluster
    - kubernetes
    - aks
    name: aks-advance-cluster
    type: application
    urls:
    - packages/aks-advance-cluster-0.1.0.tgz
    version: 0.1.0
  aks-basic-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: azure
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.65167902Z"
    description: A Helm chart for deploying AKS basic cluster
    digest: cc0a7e6a0eed6a131c0a337c6f0b83f92774d78e94b3cc8b17f67c9d06caf70f
    keywords:
    - azure
    - basic
    - cluster
    - kubernetes
    - aks
    name: aks-basic-cluster
    type: application
    urls:
    - packages/aks-basic-cluster-0.1.0.tgz
    version: 0.1.0
  aks-intermediate-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: digital
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.652359034Z"
    description: A Helm chart for deploying AKS intermediate cluster
    digest: 599ed9cb6d5793e561268d7bd32b055a0d5662257d913721d92f202fc8863879
    keywords:
    - azure
    - intermediate
    - cluster
    - kubernetes
    - aks
    name: aks-intermediate-cluster
    type: application
    urls:
    - packages/aks-intermediate-cluster-0.1.0.tgz
    version: 0.1.0
  digital-advance-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: digital
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.653066688Z"
    description: A Helm chart for deploying digital advance cluster
    digest: c5b71e31e90820046e7257d66f2633bcd70a4d10d4a8f8844518a970bb0a3417
    keywords:
    - digital-ocean
    - advance
    - cluster
    - kubernetes
    name: digital-advance-cluster
    type: application
    urls:
    - packages/digital-advance-cluster-0.1.0.tgz
    version: 0.1.0
  digital-basic-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: digital
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.653396486Z"
    description: A Helm chart for deploying digital basic cluster
    digest: a9314bfc1d6fdccd73ece1b4b196ceabcdc7be197c14f1896d17983175167664
    keywords:
    - digital-ocean
    - basic
    - cluster
    - kubernetes
    name: digital-basic-cluster
    type: application
    urls:
    - packages/digital-basic-cluster-0.1.0.tgz
    version: 0.1.0
  digital-intermediate-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: digital
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.654372702Z"
    description: A Helm chart for deploying digital intermediate cluster
    digest: 9f1a9a30ec9fb6af214311041a0a6341043b82b7c9532e2ca05d6b3a930281a1
    keywords:
    - digital-ocean
    - intermediate
    - cluster
    - kubernetes
    name: digital-intermediate-cluster
    type: application
    urls:
    - packages/digital-intermediate-cluster-0.2.0.tgz
    version: 0.2.0
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: digital
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.653840916Z"
    description: A Helm chart for deploying digital intermediate cluster
    digest: a4000ff1c381d885dd5a832f9da7e43b63ad55ab9057463743cbd185ace838a9
    keywords:
    - digital-ocean
    - intermediate
    - cluster
    - kubernetes
    name: digital-intermediate-cluster
    type: application
    urls:
    - packages/digital-intermediate-cluster-0.1.0.tgz
    version: 0.1.0
  eks-basic-cluster:
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: aws
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.654996211Z"
    description: A Helm chart for deploying AWS basic cluster
    digest: fc3395e89182dc4f74319b449e33cf972d4c99b43a279ba9c62f2e0ff5040625
    keywords:
    - aws
    - basic
    - cluster
    - kubernetes
    - eks
    name: eks-basic-cluster
    type: application
    urls:
    - packages/eks-basic-cluster-0.2.0.tgz
    version: 0.2.0
  - annotations:
      clusterType: |
        - "managedCluster"
        - "managementCluster"
      provider: aws
    apiVersion: v2
    appVersion: 1.0.0
    created: "2024-12-18T19:07:09.654692952Z"
    description: A Helm chart for deploying AWS basic cluster
    digest: db5249b9649c396ca97ff6a2a0a58c802d9082b66182a6a0c65082aea20e8bf3
    keywords:
    - aws
    - basic
    - cluster
    - kubernetes
    - eks
    name: eks-basic-cluster
    type: application
    urls:
    - packages/eks-basic-cluster-0.1.0.tgz
    version: 0.1.0
generated: "2024-12-18T19:07:09.650565253Z"
