cloudServiceProvider: "azure"
clusterName: "basiccluster"
secretName: "azure_secret"
resourceGroupName: "DefaultResourceGroup-EUS"
regionName: "eastus"

nodeGroups:
  - name: "agentpool1"
    instanceType: "Standard_DS2_v2kk"
    desiredCapacity: 22
    privateNetworking: false

