apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
data:
  cloudServiceProvider: {{ .Values.cloudServiceProvider }}
  credentialRef: {{ .Values.clusterConfig.credentialRef | default "default-credential" }}
  createClusterRequest:
    name: {{ .Values.clusterConfig.createClusterRequest.name }}
    region: {{ .Values.clusterConfig.createClusterRequest.region }}
    version: {{ .Values.clusterConfig.createClusterRequest.version }}
    nodePools:
      {{- range .Values.clusterConfig.createClusterRequest.nodePools }}
      - name: {{ .name }}
        count: {{ .count }}
        size: {{ .size }}
      {{- end }}

