name: Helm Package and Index Charts

on:
  push:
    paths:
      - 'charts/**'              # Trigger only when files under charts/ are modified
    branches:
      - gh-pages

jobs:
  helm-package-and-index:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Helm
      - name: Install Helm CLI
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm version

      # 3. Prepare folder structure
      - name: Create packages directory
        run: |
          mkdir -p charts/packages

      # 4. Package Helm charts
      - name: Package Helm Charts
        run: |
          for chart_dir in $(find charts -mindepth 1 -maxdepth 1 -type d ! -name "packages"); do
            echo "Packaging chart: $chart_dir"
            helm package "$chart_dir" --destination charts/packages
          done

      # 5. Update Helm repository index
      - name: Generate Helm index.yaml
        run: |
          helm repo index charts/packages
